spring:
  application:
    name: product-review-service
  profiles:
    active: local
  jackson:
    serialization:
      fail-on-empty-beans: 'false'

  datasource:    
    url: jdbc:postgresql://localhost:5432/ecommerce-dev-db
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  
springdoc:
  swagger-ui:
    operationsSorter: method
    path: /product-review-service-ui.html
 
server:
  port: 9300
  
  